name: Pipeline de Testes Automatizados

on:
  push:
    branches: [ "main", "master" ]          
  schedule:
    - cron: '0 11,15 * * *'
  workflow_dispatch:                        

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'             
          cache: 'npm'                      

      - name: Instalar dependências
        run: npm ci

      - name: Executar os Testes Automatizados
        run: npm run test

      - name: Upload do Relatório de Testes (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: mochawesome-report/
          retention-days: 90